// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// --- START DEBUG LOGS ---
console.log("Supabase Client Init: Using env URL =", SUPABASE_URL);
console.log("Supabase Client Init: Using env ANON_KEY =", SUPABASE_PUBLISHABLE_KEY);
// --- END DEBUG LOGS ---

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);