// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Temporarily hardcoding for debugging "invalid key" issue.
// We will revert this once the issue is resolved.
const SUPABASE_URL = "https://diuezeewlgegnwgcdpmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdWV6ZWV3bGdlZ253Z2NkcG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NzgyNzEsImV4cCI6MjA3ODQ1NDI3MX0.0JbeX6VILTrYWorwShVkQqajZbAMUYYv0jtlnqpF5Vs";

// --- START DEBUG LOGS ---
console.log("Supabase Client Init: Using hardcoded URL =", SUPABASE_URL);
console.log("Supabase Client Init: Using hardcoded ANON_KEY =", SUPABASE_PUBLISHABLE_KEY);
// --- END DEBUG LOGS ---

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);